### ISSUE TITLE
Moco HelmChart 0.4.0 : Kubernetes version dependency issue

### ISSUE THREAD

**Issue by donch** [cybozu-go/moco#483]
**Describe the bug**
We are unable to upgrade moco-controller chart version from 0.3.0 to 0.4.0 on a Kubernetes cluster 1.22 due to this change : https://github.com/cybozu-go/moco/commit/a703390608b748ec4467407097f4e5e502b98319#diff-eaa4e29fed90bbfda86f49f2c6216208669e1516c13c225dd0f775028d1ad3c5L26

This dependency isn't explained in the changelog : https://github.com/cybozu-go/moco/blob/v0.14.0/CHANGELOG.md

If there is no good reason to have this, is it possible to remote it please ? Or at least be widest in the Kubernetes supported versions. 

Thanks !

**Comment by masa213f** [comment]
Hi!

In the MOCO project, we support the latest three Kubernetes version.
And MOCO v0.14.0 supports Kubernets 1.23, 1.24, and 1.25.
So I updated the minimal Kubernetes version in the chart.

https://github.com/cybozu-go/moco/tree/v0.14.0#supported-software


However, the change may be aggressive :(
I will disscuss with my team about the policy of supported k8s version and update this settings.

**Comment by kmdkuk** [comment]
In chart version 0.4.1, the `kubeVersion` specification was reverted to 1.22 or higher.
In the future, we will have a policy of not actively updating `kubeVersion` unless there is an obvious installation problem.
However, please note that, as mentioned above, the three latest versions of Kubernetes will still be the supported versions.
This issue is now closed. Thank you!
