### ISSUE TITLE
Moco Helm chart not compatible with Kubernetes v1.26

### ISSUE THREAD

**Issue by chis0m** [cybozu-go/moco#557]
**Describe the bug**

**Environments**
- Kubernetes v1.26

**To Reproduce**
1. Execute: `helm install --namespace moco-system moco moco/moco`
2. `Error: INSTALLATION FAILED: chart requires kubeVersion: >= 1.22.0 which is incompatible with Kubernetes v1.26.7...`

**Comment by masa213f** [comment]
@chis0m 
Thank you for the report!
Does the version of your k8s cluster include preleases like `v1.26.7-foo`?
If so, it will be fixed in the next release. ref: https://github.com/cybozu-go/moco/pull/536

We will release the next version when we have completed the in-process features.
Please wait for a while.

**Comment by chis0m** [comment]
> @chis0m Thank you for the report! Does the version of your k8s cluster include preleases like `v1.26.7-foo`? If so, it will be fixed in the next release. ref: #536
> 
> We will release the next version when we have completed the in-process features. Please wait for a while.

Ok thanks

**Comment by masa213f** [comment]
@chis0m 
Sorry, it took so long.
https://github.com/cybozu-go/moco/pull/536 has been released in Chart v0.7.0. Please try it if you get the chance.
